define({
	MODULE_ADDED: 'PatchEvent.MODULE_ADDED',
	MODULE_REMOVED: 'PatchEvent.MODULE_REMOVED',
	CONNECTION_ADDED: 'PatchEvent.CONNECTION_ADDED',
	CONNECTION_PRE_REMOVE: 'PatchEvent.CONNECTION_PRE_REMOVE',
	CONNECTION_POST_REMOVE: 'PatchEvent.CONNECTION_POST_REMOVE',
	PATCH_CLEARED: 'PatchEvent.PATCH_CLEARED',
	MODULE_ATTRIBUTE_CHANGED: 'PatchEvent.MODULE_ATTRIBUTE_CHANGED',
});