import IAbstractModuleDefinitionAttribute from "./IAbstractModuleDefinitionAttribute";

interface IModuleDefinitionReadOnlyAttribute extends IAbstractModuleDefinitionAttribute
{

}

export default IModuleDefinitionReadOnlyAttribute;